package common

const (
	CodeNoError      = 0
	CodeUnknownError = -1

	MySqlNamespaceTable = "namespace"
	MySqlUserTable      = "user"

	USER_STATUS_ACTIVE   = 1
	USER_STATUS_INACTIVE = 0

	NAMESPACE_STATUS_BLOCKED   = true
	NAMESPACE_STATUS_UNBLOCKED = false

	DB_STATUS_ACTIVE   = 1
	DB_STATUS_DEACTIVE = 0
	DB_NO_LIMIT        = 0

	DB_MARK_DELETE   = 1
	DB_MARK_UNDELETE = 0

	HEADER_AUTHOR   = "Authorization"
	WSK_BASIC_CONST = "Basic"

	NAMESPACE_PREFIX_CONN = "_"

	ERROR_GENERIC            = -1
	NO_ERROR                 = 0
	ERROR_INVALID_USER       = 100
	ERROR_NOT_LOGIN          = 101
	ERROR_CONFLICT_EVENT     = 103
	ERROR_INVALID_PARAMETER  = 104
	ERROR_NOEXIST_MEETING    = 105
	ERROR_INVALID_COMMAND    = 106
	ERROR_ACCESS_DB          = 107
	ERROR_INTERNAL_EXCEPTION = 108
	ERROR_DUPLICATE_ENTRY    = 109
	ERROR_INSERT_RECORD      = 110
	ERROR_UPDATE_RECORD      = 111
	ERROR_REMOVE_RECORD      = 112
	ERROR_INVALID_TOKEN      = 113
	ERROR_TOKEN_EXPIRED      = 114
	ERROR_ACCESS_DENY        = 115
	ERROR_READ_DATA          = 116
	ERROR_INVALID_PASSWORD   = 117
	ERROR_NOEXIST_APP        = 118
	ERROR_INVALID_KEY        = 119
	ERROR_INVALID_NAME       = 120
	ERROR_INVALID_DATA       = 121
	ERROR_INVALID_DEVICE     = 122
	ERROR_OVERED_QUOTA       = 123
	ERROR_CONNECT_SERVICE    = 124
	ERROR_NOEXIST_NAMESPACE  = 125
)
